Repository jenkins-x/enhancements, pull requests merged in 2020-07, with the labels that each got.

#29 docs: add link to repo
  README.md
Labels: approved, lgtm, size/XS

#21 fix: add a trigger jenkins proposal
  proposals/trigger-jenkins/README.md
Labels: lifecycle/rotten, size/M

#26 fix: New proposal: Preview with Helmfile
  proposals/4/Dockerfile
  proposals/4/README.md
  proposals/4/helmfile.yaml
  proposals/4/jenkins-x.yml
  proposals/4/output-1.txt
  proposals/4/output-2.txt
  proposals/4/values.yaml.gotmpl
  proposals/proposals.md
Labels: size/L

#39 fix: update readme to fix rendering in jx docs
  proposals/4/Dockerfile
  proposals/4/README.md
  proposals/4/helmfile.yaml
  proposals/4/jenkins-x.yml
  proposals/4/output-1.txt
  proposals/4/output-2.txt
  proposals/4/values.yaml.gotmpl
  proposals/5/README.md
  proposals/trigger-jenkins/README.md
Labels: approved, lgtm, size/XL
